import React from 'react'

function loading() {
  return (
    <>
    <div class="loadingio-spinner-ellipsis-bwrbvt3fg2p"><div class="ldio-qduzwd214gk">
<div></div><div></div><div></div><div></div><div></div>
</div></div>
<style type="text/css">
@keyframes ldio-qduzwd214gk {
   0% { transform: translate(8.459999999999999px,56.4px) scale(0); }
  25% { transform: translate(8.459999999999999px,56.4px) scale(0); }
  50% { transform: translate(8.459999999999999px,56.4px) scale(1); }
  75% { transform: translate(56.4px,56.4px) scale(1); }
 100% { transform: translate(104.33999999999999px,56.4px) scale(1); }
}
@keyframes ldio-qduzwd214gk-r {
   0% { transform: translate(104.33999999999999px,56.4px) scale(1): }
 100% { transform: translate(104.33999999999999px,56.4px) scale(0); }
}
@keyframes ldio-qduzwd214gk-c {
   0% { background: #ebc697 }
  25% { background: #d7d1c3 }
  50% { background: #7d9c93 }
  75% { background: #bf5d6c }
 100% { background: #ebc697 }
}
.ldio-qduzwd214gk div {
  position: absolute;
  width: 28.2px;
  height: 28.2px;
  border-radius: 50%;
  transform: translate(56.4px,56.4px) scale(1);
  background: #ebc697;
  animation: ldio-qduzwd214gk 2.941176470588235s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-qduzwd214gk div:nth-child(1) {
  background: #bf5d6c;
  transform: translate(104.33999999999999px,56.4px) scale(1);
  animation: ldio-qduzwd214gk-r 0.7352941176470588s infinite cubic-bezier(0,0.5,0.5,1), ldio-qduzwd214gk-c 2.941176470588235s infinite step-start;
}.ldio-qduzwd214gk div:nth-child(2) {
  animation-delay: -0.7352941176470588s;
  background: #ebc697;
}.ldio-qduzwd214gk div:nth-child(3) {
  animation-delay: -1.4705882352941175s;
  background: #bf5d6c;
}.ldio-qduzwd214gk div:nth-child(4) {
  animation-delay: -2.205882352941176s;
  background: #7d9c93;
}.ldio-qduzwd214gk div:nth-child(5) {
  animation-delay: -2.941176470588235s;
  background: #d7d1c3;
}
.loadingio-spinner-ellipsis-bwrbvt3fg2p {
  width: 141px;
  height: 141px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-qduzwd214gk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-qduzwd214gk div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
    </>
  )
}

export default loading